\contentsline {credits}{\numberline {2.1} Cr\IeC {\'e}dit figure grande taille \url {Capture Personelle}}{9}
\contentsline {credits}{\numberline {2.2} Cr\IeC {\'e}dit figure grande taille \url {Capture Personelle}}{10}
\contentsline {credits}{\numberline {2.3} Cr\IeC {\'e}dit figure grande taille \url {Capture Personelle}}{11}
\contentsline {credits}{\numberline {2.4} Cr\IeC {\'e}dit figure grande taille \url {Capture Personelle}}{12}
